name: My CI pipeline

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: test code
      run: ls -la

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: build started
      run: echo "Build completed"

  dockerize:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: create docker image
      run: echo "docker build -t test:v1 deployment.yml"

    - name: push docker image
      run: echo "docker push test:v1"

  deploy:
    needs: dockerize
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: deploy on kuber
      run: echo "kubectl apply -f deployment.yml"